# Nombre app (opcional)
spring.application.name=automation-platform

# Perfil activo
spring.profiles.active=dev

# Datasource (usa variables de entorno)
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA: que NO cree tablas (Flyway manda)
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true